language: "ko-KR"
reviews:
  profile: "chill"
  level: basic
  enable_auto_review: true
  high_level_summary: true
  sequence_diagrams: true
  assess_linked_issues: true
  suggested_reviewers: true
  auto_assign_reviewers: true
  auto_review_on:
    - pull_request
